import './globals.css'
import { Mulish } from 'next/font/google'
import Footer from './(components)/Footer/page'
import Header from './(components)/Header/page'

const mulish = Mulish({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
